services:
  app:
    build: .
    container_name: FitnesApp
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  postgres:
    #Проверяет, есть ли у тебя локально образ postgres:16
    image: postgres:16
    #---------------------------------------------------
    container_name: DataBase
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: demo_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
        - redis_data:/data
volumes:
  postgres_data:
    name: postgres_data

  redis_data:
      name: redis_data