package project;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

// eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwicm9sZSI6IkNMSUVOVCIsImlhdCI6MTc4NDczMjUxNiwiZXhwIjoxNzg1OTQyMTE2fQ.KtOJ4UU1Pbi6hkZPGlQRAjYBKSYqH05WCobXv3QCTj3mj8KwiK_haJOHpjlI7jWgqJyy69lW7getD9sdDAXxHw
// eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzIiwicm9sZSI6IkNMSUVOVCIsImlhdCI6MTc4NDgzODAyNiwiZXhwIjoxNzg2MDQ3NjI2fQ.dHatvHKsW0nUu6C7IeSfkCnA4o9hBicE0FNbfrb-SnSqezAKxUPcrPaC-e9cSKsjE1dztwaiYC2wyeD_vBGcWQ
// adm eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwicm9sZSI6IkFETUlOSVNUUkFUT1IiLCJpYXQiOjE3ODQ4MzcxMDgsImV4cCI6MTc4NjA0NjcwOH0.wAdQ4rgawIRe5jmcFDbzLMZiq3XfxYixi6CG6cPKqPTai7WpmhRCS3jkMzmH4LAthIuodtOk5MTP0NgTSp9jRg
@SpringBootApplication
public class JymApplication {
    public static void main(String[] args) {
        SpringApplication.run(JymApplication.class, args);
    }
}